language: python
python: 3.5
sudo: false
branches:
  only:
  - master
  - develop
services:
- docker
env:
  global:
  - AWS_ACCESS_KEY_ID='foo' AWS_DEFAULT_REGION='us-east-1' AWS_SECRET_ACCESS_KEY='bar'
    SQS_IP=127.0.0.1 SQS_PORT=5000
  matrix:
  - TOXENV=py35
install:
- docker run -d -p 127.0.0.1:5000:5000 --name sqs briefy/aws-test:latest sqs
- pip install -r requirements/dev.txt
- pip install flake8
script:
- tox -e ${TOXENV}
- flake8 src/briefy/choreographer setup.py
after_success:
- make docs
notifications:
  slack: robyandjack:qxjOPwcrGEtVx3aCQBr812t9
deploy:
  provider: deis
  controller: https://deis.stg.briefy.co
  cli_version: v2.2.0
  app: briefy-choreographer
  username: ci
  password:
    secure: AOJ4Rjf2WPRslLgXV4hzm8ctow1ejHs0lrGYb3GG3w41AQtNyHwEjq7IeSZgzPUd6uxzDVCzjHfkUd+B0XNX30SgD7/GBKDXpfgJseBMQ/HYB8XTn7gs5hK9aQ/IiztigeSHmc4x9QMIrfsgetV7ug1LNUerzTKHmRRA86ERlyafS1eHOBJMXJrqqRjHRedJ7zgfhFgBFIvqCtzAmzVkRiwn3pe6VJwk1FsZbKOttvI1uIRI9ZUCodnjze6mPPY6+qviGR0tpVOVO1sx9efek14BBFX04cOlYo5MUw3R4Sm24wPWgPfHM9h6sSCY92oTgMeMDGBNcAVanfqHdt37bdVmP5+TqeKU5SaGIklNDKx7VGQ3wNQdRx9xbJ41WjS6+NtGP5U9ENIA9NADQicrch8C5XKr+xyXk7nx53yHMQ/O7I2hIBPklJZQRG7hRkkumIzBufxuUzxE/62rh8QydX6CBwVuseUu9Der0A7t9eN/VTed5Xtz1SFSWLIWCkfmkGsLqwp85oL0tdLFWrs5813dYIA/31+iFJxijCCqduerfsvWn4/wloX7M7y4JFicdYSLTegfutRX3NNBSAgReQoP2QEVOpMz+dHnDqd5zWxq+9yCj39KXFvS5aIaMZJYZOgpm/xX8CHUZFEISLZcfg5rIHiJRMgHmKCDckeNzZs=
  edge:
    source: mattk42/dpl
    branch: deis-v2-exit-status
  on:
    repo: BriefyHQ/briefy.choreographer
    branch: develop
